Repository fga-eps-mds/2019.2-Gymnasteg-Backend, pull requests merged in 2019-11, with the labels that each got.

#22 Feature/114 us13#dashboard do arbitro
  package.json
  src/app/controllers/AthleteController.js
  src/app/controllers/JudgeManagement.js
  src/app/models/Stand.js
  src/database/seeders/20191009234952-seed-modality.js
  src/database/seeders/20191010181116-seed-coordinator.js
  src/routes.js
  src/server.js
  yarn.lock
Labels: bug, enhancement

#24 Feature/configurar codecov
  .travis.yml
  README.md
  codecov.yml
  package.json
Labels: documentation, enhancement

#35 Feature/53 US10# Votação
  src/app/controllers/JudgeManagement.js
  src/app/models/Athlete.js
  src/app/models/Vote.js
  src/database/migrations/20191026172016-create-votes.js
  src/routes.js
  src/server.js
Labels: enhancement
